list_word = [ 
    'apple',
    'banana', 
    'blackberry', 
    'cherry', 
    'lemon', 
    'kiwi', 
    'orange', 
    'grapes', 
    'lime', 
    'mango', 
    'peach',
    'pineapple',
    'raisins',
    'strawberry',
    'watermelon']